Lecture03課題提出
makoto-raisetech/Raisetech pull request #11
Opened 2024-04-15 14:54 UTC by makoto-raisetech

第3回課題提出します。
ご確認よろしくお願いします。

2024-04-16 03:47 UTC, MasatoshiMizumoto requested changes
中身としては大丈夫ですが、指摘入れた部分の解消をお願いします！！
あとDraftなので変更点がないなら正式なPRに変更お願いします！！

2024-04-16 03:47 UTC, MasatoshiMizumoto commented on images/puma-version.png
デスクトップ上に人名のようなものがありますが大丈夫でしょうか？？ご確認ください！

2024-04-16 13:28 UTC, makoto-raisetech commented on images/puma-version.png
ご指摘ありがとうございます。画像差し替えします。

2024-04-17 14:19 UTC, MasatoshiMizumoto approved these changes
LGTMです！

2024-04-20 15:26 UTC, merged